# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "2.7"

env:
  global:
    - TEST_DB_USER="postgres"
  matrix:
    - DJANGO="Django>=1.8,<1.9"
    - DJANGO="Django>=1.7,<1.8"
    - DJANGO="Django>=1.6,<1.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements-test.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script:
  - coverage run --source=teryt runtests.py 

after_success:
  - pip install --quiet coveralls
  - coveralls

addons:
  postgresql: "9.4"

# Needed for Django 1.6
before_script:
  - psql -c 'create database django_teryt;' -U postgres

